2021-10-23 08:54:58.010 | INFO     |  5799 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-23 08:54:58.017 | ERROR    |  5799 | mycroft_bus_client.client.client | === ConnectionRefusedError(111, 'Connection refused') ===
Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
2021-10-23 08:54:58.017 | ERROR    |  5799 | mycroft_bus_client.client.client | Exception closing websocket: ConnectionRefusedError(111, 'Connection refused')
2021-10-23 08:54:58.017 | WARNING  |  5799 | mycroft_bus_client.client.client | Message Bus Client will reconnect in 5 seconds.
2021-10-23 08:55:03.022 | INFO     |  5799 | mycroft_bus_client.client.client | Connected
2021-10-23 08:55:03.024 | INFO     |  5799 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-23 08:55:03.028 | INFO     |  5799 | mycroft.skills.msm_wrapper:create_msm:96 | Acquiring lock to instantiate MSM
2021-10-23 08:55:03.028 | INFO     |  5799 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-23 08:55:04.045 | INFO     |  5799 | mycroft.skills.msm_wrapper:create_msm:112 | Releasing MSM instantiation lock.
2021-10-23 08:55:04.046 | INFO     |  5799 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-23 08:55:03.045838
2021-10-23 08:55:04.046 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-pairing
2021-10-23 08:55:05.749 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:05.757 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-pairing
2021-10-23 08:55:05.757 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:05.758 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-pairing.mycroftai
2021-10-23 08:55:05.766 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-23 08:55:05.773 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-pairing.mycroftai
2021-10-23 08:55:05.774 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-23 08:55:05.774 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-pairing.mycroftai loaded successfully
2021-10-23 08:55:05.775 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-volume
2021-10-23 08:55:06.599 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:06.607 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-23 08:55:07.482 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-volume
2021-10-23 08:55:07.483 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:07.517 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-volume.mycroftai
2021-10-23 08:55:07.527 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-23 08:55:07.571 | ERROR    |  5799 | VolumeSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-23 08:55:10.572 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-volume.mycroftai
2021-10-23 08:55:10.573 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-23 08:55:10.574 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-volume.mycroftai loaded successfully
2021-10-23 08:55:10.575 | INFO     |  5799 | __main__:on_started:177 | Skills service is starting up.
2021-10-23 08:55:10.679 | INFO     |  5799 | __main__:_update_system:154 | Attempting system update...
2021-10-23 08:55:13.681 | INFO     |  5799 | mycroft.enclosure.display_manager:_write_data:70 | Display Manager is creating /tmp/mycroft/ipc/managers/disp_info
2021-10-23 08:55:13.681 | INFO     |  5799 | __main__:_ensure_device_is_paired:133 | Device not paired, invoking the pairing skill
2021-10-23 08:55:13.687 | INFO     |  5799 | __main__:on_alive:181 | Skills service is alive.
2021-10-23 08:55:13.688 | INFO     |  5799 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-23 08:55:13.967 | INFO     |  5799 | PairingSkill | Communicating account URL to user
2021-10-23 08:55:14.636 | WARNING  |  5799 | msm.mycroft_skills_manager | No such default skill: mycroft-pandora
2021-10-23 08:55:14.637 | INFO     |  5799 | mycroft.skills.skill_manager:run:234 | Not all default skills are installed, performing skill update...
2021-10-23 08:55:14.637 | INFO     |  5799 | mycroft.skills.skill_updater:update_skills:149 | Beginning skill update...
2021-10-23 08:55:14.752 | INFO     |  5799 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-23 08:55:15.836 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:15.853 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-unknown
2021-10-23 08:55:15.857 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-wolfram-alpha
2021-10-23 08:55:15.858 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-alarm
2021-10-23 08:55:15.859 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-audio-record
2021-10-23 08:55:15.859 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-configuration
2021-10-23 08:55:15.860 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-date-time
2021-10-23 08:55:15.865 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-duckduckgo
2021-10-23 08:55:15.883 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-hello-world
2021-10-23 08:55:15.884 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-ip
2021-10-23 08:55:15.885 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-joke
2021-10-23 08:55:15.920 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-personal
2021-10-23 08:55:15.901 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-naptime
2021-10-23 08:55:15.930 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-singing
2021-10-23 08:55:15.915 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-npr-news
2021-10-23 08:55:15.912 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-playback-control
2021-10-23 08:55:15.896 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-installer
2021-10-23 08:55:15.940 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-reminder
2021-10-23 08:55:16.662 | ERROR    |  5799 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant.mycroftai: MergeConflict
2021-10-23 08:55:16.664 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-speak
2021-10-23 08:55:16.953 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:16.981 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-audio-record
2021-10-23 08:55:17.212 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.282 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.304 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.357 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.359 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.363 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.399 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-fallback-duck-duck-go
2021-10-23 08:55:17.400 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-naptime
2021-10-23 08:55:17.400 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.401 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-spelling
2021-10-23 08:55:17.403 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-personal
2021-10-23 08:55:17.405 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.407 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-stop
2021-10-23 08:55:17.438 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-ip
2021-10-23 08:55:17.450 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.491 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.497 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-reminder
2021-10-23 08:55:17.498 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.499 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-support
2021-10-23 08:55:17.513 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.527 | INFO     |  5799 | msm.skill_entry | Nothing new for mycroft-volume
2021-10-23 08:55:17.539 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-joke
2021-10-23 08:55:17.632 | INFO     |  5799 | msm.skill_entry | Successfully installed fallback-unknown
2021-10-23 08:55:17.632 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.633 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/mycroft-timer
2021-10-23 08:55:17.635 | INFO     |  5799 | msm.skill_entry | Nothing new for mycroft-pairing
2021-10-23 08:55:17.636 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-configuration
2021-10-23 08:55:17.637 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-playback-control
2021-10-23 08:55:17.637 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.637 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-weather
2021-10-23 08:55:17.654 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.674 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.690 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.795 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:17.810 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-23 08:55:17.819 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-version-checker
2021-10-23 08:55:17.844 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-speak
2021-10-23 08:55:17.845 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:17.850 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-wiki
2021-10-23 08:55:17.960 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-date-time
2021-10-23 08:55:17.991 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.037 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.071 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-hello-world
2021-10-23 08:55:18.072 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:18.073 | INFO     |  5799 | msm.skill_entry | Downloading skill: https://github.com/MycroftAI/skill-query
2021-10-23 08:55:18.140 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for fallback-wolfram-alpha
2021-10-23 08:55:18.284 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.299 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.338 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-alarm
2021-10-23 08:55:18.376 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-installer
2021-10-23 08:55:18.407 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.470 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-npr-news
2021-10-23 08:55:18.473 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.525 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-spelling
2021-10-23 08:55:18.529 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:18.606 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.618 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:18.672 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-support-helper
2021-10-23 08:55:18.687 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-stop
2021-10-23 08:55:18.688 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:18.943 | ERROR    |  5799 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant: MergeConflict
2021-10-23 08:55:19.058 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:19.065 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:19.087 | INFO     |  5799 | msm.skill_entry | Successfully installed fallback-query
2021-10-23 08:55:19.088 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:19.131 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-wiki
2021-10-23 08:55:19.185 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:19.246 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-timer
2021-10-23 08:55:19.246 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:19.365 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:19.386 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-singing
2021-10-23 08:55:19.387 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:19.687 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:19.718 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-version-checker
2021-10-23 08:55:19.718 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:19.838 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-audio-record
2021-10-23 08:55:19.839 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:20.345 | INFO     |  5799 | msm.skill_entry | Installing system requirements...
2021-10-23 08:55:20.366 | INFO     |  5799 | msm.skill_entry | Installing requirements.txt for mycroft-weather
2021-10-23 08:55:21.069 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-fallback-duck-duck-go
2021-10-23 08:55:21.070 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:21.911 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-ip
2021-10-23 08:55:21.911 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:23.020 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-joke
2021-10-23 08:55:23.021 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:25.228 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-configuration
2021-10-23 08:55:25.229 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:40.567 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-date-time
2021-10-23 08:55:40.568 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:44.201 | INFO     |  5799 | msm.skill_entry | Successfully installed fallback-wolfram-alpha
2021-10-23 08:55:44.202 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:44.304 | INFO     |  5799 | PairingSkill | Initiating device pairing sequence...
2021-10-23 08:55:44.304 | INFO     |  5799 | PairingSkill | Retrieving pairing code from device API...
2021-10-23 08:55:44.562 | INFO     |  5799 | PairingSkill | Pairing code obtained: JLC3P9
2021-10-23 08:55:44.562 | INFO     |  5799 | PairingSkill | Communicating pairing URL to user
2021-10-23 08:55:44.982 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-alarm
2021-10-23 08:55:44.983 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:45.844 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-installer
2021-10-23 08:55:45.844 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:49.082 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-npr-news
2021-10-23 08:55:49.082 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:53.065 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-support-helper
2021-10-23 08:55:53.065 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:55.203 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-wiki
2021-10-23 08:55:55.203 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:56.069 | INFO     |  5799 | msm.skill_entry | Successfully installed mycroft-weather
2021-10-23 08:55:56.069 | INFO     |  5799 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-23 08:55:56.091 | INFO     |  5799 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-23 09:55:56.090826
2021-10-23 08:55:56.091 | INFO     |  5799 | mycroft.skills.skill_updater:update_skills:170 | Skill update complete
2021-10-23 08:55:56.091 | INFO     |  5799 | mycroft.skills.skill_manager:_load_on_startup:273 | Loading installed skills...
2021-10-23 08:55:56.092 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-ip.mycroftai
2021-10-23 08:55:56.140 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-23 08:55:56.156 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-ip.mycroftai
2021-10-23 08:55:56.157 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-23 08:55:56.157 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-ip.mycroftai loaded successfully
2021-10-23 08:55:56.158 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-reminder.mycroftai
2021-10-23 08:55:56.209 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-23 08:55:56.251 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-reminder.mycroftai
2021-10-23 08:55:56.252 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-23 08:55:56.254 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-reminder.mycroftai loaded successfully
2021-10-23 08:55:56.255 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-installer.mycroftai
2021-10-23 08:55:56.260 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-23 08:55:56.285 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-installer.mycroftai
2021-10-23 08:55:56.286 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-23 08:55:56.289 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-installer.mycroftai loaded successfully
2021-10-23 08:55:56.289 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-version-checker.mycroftai
2021-10-23 08:55:56.293 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-23 08:55:56.316 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-version-checker.mycroftai
2021-10-23 08:55:56.317 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-23 08:55:56.318 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-version-checker.mycroftai loaded successfully
2021-10-23 08:55:56.318 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-singing.mycroftai
2021-10-23 08:55:56.344 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-23 08:55:56.361 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-singing.mycroftai
2021-10-23 08:55:56.361 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-23 08:55:56.364 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-singing.mycroftai loaded successfully
2021-10-23 08:55:56.364 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-joke.mycroftai
2021-10-23 08:55:56.368 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-23 08:55:56.391 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-joke.mycroftai
2021-10-23 08:55:56.392 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-23 08:55:56.393 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-joke.mycroftai loaded successfully
2021-10-23 08:55:56.394 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-timer.mycroftai
2021-10-23 08:55:56.414 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-23 08:55:56.463 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-timer.mycroftai
2021-10-23 08:55:56.464 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-23 08:55:56.465 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-timer.mycroftai loaded successfully
2021-10-23 08:55:56.466 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: homeassistant.mycroftai
2021-10-23 08:55:56.696 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-23 08:55:56.697 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-23 08:55:56.755 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill homeassistant.mycroftai loaded successfully
2021-10-23 08:55:56.755 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-alarm.mycroftai
2021-10-23 08:55:56.781 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-23 08:55:56.781 | ERROR    |  5799 | AlarmSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-23 08:55:56.823 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-alarm.mycroftai
2021-10-23 08:55:56.824 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-23 08:55:56.825 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-alarm.mycroftai loaded successfully
2021-10-23 08:55:56.826 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-naptime.mycroftai
2021-10-23 08:55:56.829 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-23 08:55:56.837 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-naptime.mycroftai
2021-10-23 08:55:56.839 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-23 08:55:56.842 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-naptime.mycroftai loaded successfully
2021-10-23 08:55:56.842 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-spelling.mycroftai
2021-10-23 08:55:56.844 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-23 08:55:56.856 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-spelling.mycroftai
2021-10-23 08:55:56.857 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-23 08:55:56.859 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-spelling.mycroftai loaded successfully
2021-10-23 08:55:56.860 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-fallback-duck-duck-go.mycroftai
2021-10-23 08:55:56.866 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
2021-10-23 08:55:56.882 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-fallback-duck-duck-go.mycroftai
2021-10-23 08:55:56.883 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
2021-10-23 08:55:56.885 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-fallback-duck-duck-go.mycroftai loaded successfully
2021-10-23 08:55:56.885 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-npr-news.mycroftai
2021-10-23 08:55:56.941 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-npr-news.mycroftai/settings.json
2021-10-23 08:55:57.965 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-npr-news.mycroftai
2021-10-23 08:55:57.966 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-npr-news.mycroftai/settings.json
2021-10-23 08:55:57.967 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-npr-news.mycroftai loaded successfully
2021-10-23 08:55:57.967 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-support-helper.mycroftai
2021-10-23 08:55:57.974 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-support-helper.mycroftai/settings.json
2021-10-23 08:55:57.981 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-support-helper.mycroftai
2021-10-23 08:55:57.982 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-support-helper.mycroftai/settings.json
2021-10-23 08:55:57.984 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-support-helper.mycroftai loaded successfully
2021-10-23 08:55:57.984 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-weather.mycroftai
2021-10-23 08:55:58.000 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-weather.mycroftai/settings.json
2021-10-23 08:55:58.097 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-weather.mycroftai
2021-10-23 08:55:58.098 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-weather.mycroftai/settings.json
2021-10-23 08:55:58.098 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-weather.mycroftai loaded successfully
2021-10-23 08:55:58.098 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-speak.mycroftai
2021-10-23 08:55:58.101 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-speak.mycroftai/settings.json
2021-10-23 08:55:58.115 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-speak.mycroftai
2021-10-23 08:55:58.115 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-speak.mycroftai/settings.json
2021-10-23 08:55:58.116 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-speak.mycroftai loaded successfully
2021-10-23 08:55:58.116 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-audio-record.mycroftai
2021-10-23 08:55:58.122 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-23 08:55:58.134 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-audio-record.mycroftai
2021-10-23 08:55:58.134 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-23 08:55:58.135 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-audio-record.mycroftai loaded successfully
2021-10-23 08:55:58.135 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-stop.mycroftai
2021-10-23 08:55:58.140 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-stop.mycroftai/settings.json
2021-10-23 08:55:58.154 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-stop.mycroftai
2021-10-23 08:55:58.155 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-stop.mycroftai/settings.json
2021-10-23 08:55:58.155 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-stop.mycroftai loaded successfully
2021-10-23 08:55:58.156 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-hello-world.mycroftai
2021-10-23 08:55:58.158 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-hello-world.mycroftai/settings.json
2021-10-23 08:55:58.169 | INFO     |  5799 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-hello-world.mycroftai
2021-10-23 08:55:58.169 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-hello-world.mycroftai/settings.json
2021-10-23 08:55:58.170 | INFO     |  5799 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-hello-world.mycroftai loaded successfully
2021-10-23 08:55:58.170 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-date-time.mycroftai
2021-10-23 08:55:58.395 | ERROR    |  5799 | mycroft_bus_client.client.client | === ConnectionResetError(104, 'Connection reset by peer') ===
Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 128, in on_error
    self.emitter.emit('error', error)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 305, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 53, in read
    if not read_callback():
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 271, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-10-23 08:55:58.395 | ERROR    |  5799 | mycroft_bus_client.client.client | Exception closing websocket: ConnectionResetError(104, 'Connection reset by peer')
2021-10-23 08:55:58.395 | WARNING  |  5799 | mycroft_bus_client.client.client | Message Bus Client will reconnect in 5 seconds.
2021-10-23 08:55:58.503 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-date-time.mycroftai/settings.json
2021-10-23 08:55:58.507 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-date-time.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.508 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-configuration.mycroftai
2021-10-23 08:55:58.513 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-23 08:55:58.518 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-23 08:55:58.518 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-configuration.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.519 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-query.mycroftai
2021-10-23 08:55:58.522 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-query.mycroftai/settings.json
2021-10-23 08:55:58.526 | INFO     |  5799 | QuestionsAnswersSkill | Removing all handlers...
2021-10-23 08:55:58.526 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-query.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.527 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-personal.mycroftai
2021-10-23 08:55:58.529 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-personal.mycroftai/settings.json
2021-10-23 08:55:58.533 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-personal.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 305, in _create_skill_instance
    self.instance._register_decorated()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 749, in _register_decorated
    self.register_intent(intent, method)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 985, in register_intent
    return self.register_intent_file(intent_parser, handler)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1022, in register_intent_file
    self.intent_service.register_padatious_intent(name, filename)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 129, in register_padatious_intent
    self.bus.emit(Message("padatious:register_intent", data))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.533 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-wolfram-alpha.mycroftai
2021-10-23 08:55:58.553 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai/settings.json
2021-10-23 08:55:58.559 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.559 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-wiki.mycroftai
2021-10-23 08:55:58.564 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-wiki.mycroftai/settings.json
2021-10-23 08:55:58.567 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-wiki.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.568 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-unknown.mycroftai
2021-10-23 08:55:58.571 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-unknown.mycroftai/settings.json
2021-10-23 08:55:58.574 | INFO     |  5799 | UnknownSkill | Removing all handlers...
2021-10-23 08:55:58.575 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-unknown.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.575 | INFO     |  5799 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-playback-control.mycroftai
2021-10-23 08:55:58.582 | INFO     |  5799 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-playback-control.mycroftai/settings.json
2021-10-23 08:55:58.588 | ERROR    |  5799 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-playback-control.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-23 08:55:58.588 | INFO     |  5799 | mycroft.skills.skill_manager:_load_on_startup:275 | Skills all loaded!
2021-10-23 08:56:03.403 | INFO     |  5799 | mycroft_bus_client.client.client | Connected
2021-10-23 08:56:14.899 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-23 08:56:15.202 | INFO     |  5799 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
